name: Test and Lint

on:
  push: 
    branches: [main]
  workflow_dispatch: {}   # Manual Trigger allow


jobs:
  Lint:   # Job name
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app/
    steps:
      - name: Checkout the code
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: "app/package-lock.json"
        
      - name: Install Depdendencies
        run: npm install

      - name: Linting
        run: npm run lint

  Test:
    needs: Lint   # Only run when Lint job passed
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app/
    steps:
      - name: Checkout the code
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: "app/package-lock.json"
          
      - name: Install Depdendencies
        run: npm install

      - name: Testing
        run: npm test 
        
    